(function () {
  "use strict";
  const engine = window.PhysicsEngine;
  const catalog = window.PHYSICS_CATALOG;
  const $ = id => document.getElementById(id);
  const els = {clock:$("stationClock"),mode:$("modeLabel"),title:$("nowTitle"),programTime:$("programTime"),enter:$("enterButton"),stationCard:$("stationCard"),cardLabel:$("stationCardLabel"),cardTitle:$("stationCardTitle"),cardCountdown:$("stationCardCountdown"),startOver:$("startOverButton"),rewind:$("rewindButton"),live:$("liveButton"),share:$("shareButton"),shareStatus:$("shareStatus"),position:$("positionLabel"),remaining:$("remainingLabel"),progress:$("progressBar"),next:$("nextCards"),guide:$("guideRows"),guideDate:$("guideDate"),vault:$("vaultGrid")};
  let player=null,playerReady=false,apiRequested=false,entered=false,loadedKey="",loadedVideoId="",scheduleKey="",schedule=[],mode="live",timeShiftBaseMs=0,timeShiftStartedMs=0;
  const failedIds=new Set();
  const activeClockMs=()=>mode==="live"?Date.now():timeShiftBaseMs+(Date.now()-timeShiftStartedMs);
  function ensureSchedule(nowMs){const key=engine.dateKey(nowMs);if(key===scheduleKey&&schedule.length)return;scheduleKey=key;try{schedule=engine.createDaySchedule(nowMs,catalog);renderGuide();}catch(e){schedule=[];showMessage("PHYSICS TV","Program sources are being refreshed.","Please try again shortly.");}}
  function fmtTime(ms){return new Intl.DateTimeFormat("en-US",{timeZone:engine.TIME_ZONE,hour:"numeric",minute:"2-digit"}).format(new Date(ms));}
  function fmtDuration(seconds){const m=Math.max(0,Math.ceil(seconds/60));return m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m} min`;}
  function art(program){return program&&program.videoId?`https://i.ytimg.com/vi/${program.videoId}/maxresdefault.jpg`:"https://i.ytimg.com/vi/XtMmeAjQTXc/maxresdefault.jpg";}
  function hue(program){let h=0;for(const c of program.title)h=((h<<5)-h+c.charCodeAt(0))|0;return 185+(Math.abs(h)%90);}
  function setArt(program){document.body.style.setProperty("--program-hue",hue(program));document.body.style.setProperty("--program-art",`url("${art(program)}")`);}
  function renderGuide(){if(!schedule.length)return;els.guideDate.textContent=new Intl.DateTimeFormat("en-US",{timeZone:engine.TIME_ZONE,weekday:"long",month:"long",day:"numeric"}).format(new Date(schedule[0].startsAtMs));els.guide.innerHTML=schedule.map(item=>`<article class="guide-row" data-id="${item.id}"><time>${fmtTime(item.startsAtMs)}</time><strong>${item.program.title}</strong><span>${item.label} · ${item.program.collection}</span></article>`).join("");}
  function renderVault(){els.vault.innerHTML=(catalog.vault||[]).map((title,i)=>`<article class="vault-card"><span>${String(i+1).padStart(2,"0")}</span><strong>${title}</strong></article>`).join("");}
  function nextItems(block){const i=schedule.findIndex(x=>x.id===block.id),items=i>=0?schedule.slice(i+1):[];if(items.length<3){try{items.push(...engine.createDaySchedule(block.endsAtMs+1000,catalog));}catch(_){}}return items.slice(0,3);}
  let renderedNext="";
  function renderNext(block){const key=block?`${block.id}:${block.program.videoId}`:"";if(key===renderedNext)return;renderedNext=key;els.next.innerHTML=nextItems(block).map(item=>`<article class="next-card" style="--card-art:url('${art(item.program)}')"><time>${fmtTime(item.startsAtMs)}</time><div><h3>${item.program.title}</h3><p>${item.label} · ${item.program.collection}</p></div></article>`).join("");}
  function showMessage(label,title,detail){els.stationCard.hidden=false;els.cardLabel.textContent=label;els.cardTitle.textContent=title;els.cardCountdown.textContent=detail;}
  function showStation(state){if(failedIds.has(state.segment.videoId||state.block.program.videoId)){showMessage("SOURCE UNAVAILABLE",state.block.program.title,`The schedule stays fixed. Next program starts at ${fmtTime(state.block.endsAtMs)}.`);}else{showMessage(state.block.label,state.segment.title,`${fmtDuration(state.segmentRemaining)} until the next scheduled program`);}}
  function loadMedia(state){if(!entered||!state)return;const id=state.segment.videoId,failed=id&&failedIds.has(id),playable=id&&state.segment.cleared&&!failed;const key=`${state.block.id}:${state.segment.stationStart}:${id}:${failed}`;if(!playable){showStation(state);if(playerReady&&loadedKey!==key)player.stopVideo();loadedKey=key;return;}els.stationCard.hidden=true;if(!playerReady)return;if(loadedKey!==key){loadedKey=key;loadedVideoId=id;player.loadVideoById({videoId:id,startSeconds:state.mediaSeconds});return;}if(mode==="live"&&window.YT&&player.getPlayerState()===YT.PlayerState.PLAYING){const drift=state.mediaSeconds-player.getCurrentTime();if(Math.abs(drift)>3)player.seekTo(state.mediaSeconds,true);}}
  function tick(){const now=activeClockMs();ensureSchedule(now);if(!schedule.length)return;const state=engine.resolve(now,schedule);els.clock.textContent=`${fmtTime(Date.now())} local`;els.mode.textContent=mode==="live"?`LIVE · ${state.block.label}`:"TIME SHIFTED";els.title.textContent=state.block.program.title;els.programTime.textContent=`${fmtTime(state.block.startsAtMs)}–${fmtTime(state.block.endsAtMs)}`;els.position.textContent=mode==="live"?`Synced with the ${state.block.label.toLowerCase()} schedule`:`${fmtDuration(state.blockElapsed)} from block start`;els.remaining.textContent=`${fmtDuration(state.blockRemaining)} until next scheduled program`;els.progress.style.width=`${Math.min(100,(state.blockElapsed/state.block.blockSeconds)*100)}%`;setArt(state.block.program);document.querySelectorAll(".guide-row").forEach(row=>row.classList.toggle("current",row.dataset.id===state.block.id));renderNext(state.block);loadMedia(state);}
  function loadApi(){if(apiRequested||playerReady)return;apiRequested=true;if(window.YT&&window.YT.Player)return window.onYouTubeIframeAPIReady();const tag=document.createElement("script");tag.src="https://www.youtube.com/iframe_api";tag.referrerPolicy="strict-origin-when-cross-origin";document.head.appendChild(tag);}
  function enter(){entered=true;els.enter.hidden=true;loadApi();tick();}
  function startOver(){ensureSchedule(Date.now());if(!schedule.length)return;const live=engine.resolve(Date.now(),schedule);mode="timeshift";timeShiftBaseMs=live.block.startsAtMs;timeShiftStartedMs=Date.now();loadedKey="";tick();}
  function rewind(){mode="timeshift";timeShiftBaseMs=activeClockMs()-30000;timeShiftStartedMs=Date.now();loadedKey="";tick();}
  function joinLive(){mode="live";loadedKey="";scheduleKey="";tick();}
  function creditShare(){const key="infinity_channel_share_progress_v1";let p=0;try{p=Number(localStorage.getItem(key))||0;}catch(_){}p+=1;const awarded=p>=10;if(awarded)p=0;try{localStorage.setItem(key,String(p));}catch(_){}return{progress:p,awarded};}
  async function shareChannel(){const current=els.title.textContent&&!els.title.textContent.includes("Loading")?els.title.textContent:"Physics TV";const payload={title:`${current} · Physics TV`,text:`Watch ${current} on Physics TV.`,url:location.href};try{if(navigator.share){await navigator.share(payload);const r=creditShare();els.shareStatus.textContent=r.awarded?"Shared · 1 StarCoin completed!":`Shared · StarCoin progress ${r.progress}/10`;}else{await navigator.clipboard.writeText(payload.url);els.shareStatus.textContent="Physics TV link copied.";}}catch(e){if(!e||e.name!=="AbortError")els.shareStatus.textContent="Share did not complete.";}}
  window.onYouTubeIframeAPIReady=function(){player=new YT.Player("player",{width:"100%",height:"100%",playerVars:{playsinline:1,controls:0,rel:0,modestbranding:1,iv_load_policy:3,fs:0,enablejsapi:1,origin:location.origin,widget_referrer:location.href},events:{onReady:()=>{playerReady=true;player.unMute();player.setVolume(100);tick();},onError:()=>{if(loadedVideoId)failedIds.add(loadedVideoId);loadedVideoId="";loadedKey="";setTimeout(tick,150);}}});};
  els.enter.addEventListener("click",enter);els.startOver.addEventListener("click",startOver);els.rewind.addEventListener("click",rewind);els.live.addEventListener("click",joinLive);els.share.addEventListener("click",shareChannel);renderVault();ensureSchedule(Date.now());tick();setInterval(tick,1000);
})();
