(function(){
  "use strict";
  const engine=window.PhysicsEngine,catalog=window.PHYSICS_CATALOG,guide=document.querySelector(".guide");
  if(!engine||!catalog||!guide)return;
  const safe=v=>String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const fmtDay=ms=>new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric"}).format(new Date(ms));
  const fmtLong=ms=>new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date(ms));
  const fmtTime=ms=>new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(ms));
  const art=p=>p&&p.videoId?`https://i.ytimg.com/vi/${encodeURIComponent(p.videoId)}/hqdefault.jpg`:"";
  function localNoon(offset){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+offset);return d.getTime();}
  const days=Array.from({length:7},(_,i)=>{const blocks=engine.createDaySchedule(localNoon(i),catalog);return{startsAtMs:blocks[0].startsAtMs,blocks};});
  let selected=0;const now=Date.now();
  function card(block){const p=block.program||{};return `<article class="physics-guide-card"><img src="${safe(art(p))}" alt="" loading="lazy"><div><time>${safe(fmtTime(block.startsAtMs))}</time><span>${safe(block.label)}</span><strong>${safe(p.title||"Scheduled program")}</strong><small>${safe(p.collection||p.source||"")}</small></div></article>`;}
  const style=document.createElement("style");style.textContent=`.physics-weekly{display:grid;gap:15px}.physics-weekly-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.physics-weekly-head h2{margin:0;font:800 clamp(1.7rem,4vw,3rem)/1 Georgia,serif}.physics-weekly-head p{margin:0 0 7px;color:#6edcff;font-size:11px;font-weight:950;letter-spacing:.15em}.physics-day-tabs{display:flex;gap:7px;overflow:auto;padding:2px}.physics-day-tabs button{flex:0 0 auto;min-height:40px;padding:0 12px;border:1px solid rgba(255,255,255,.15);border-radius:999px;background:#0a1422;color:#fff;font-weight:800}.physics-day-tabs button[aria-current=date]{border-color:#68ddff;background:rgba(80,202,255,.14)}.physics-guide-date{margin:4px 0 0;font:800 1.45rem Georgia,serif}.physics-guide-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.physics-guide-card{overflow:hidden;display:grid;grid-template-columns:120px 1fr;min-height:118px;border:1px solid rgba(255,255,255,.12);border-radius:15px;background:rgba(7,15,27,.8)}.physics-guide-card img{width:120px;height:100%;min-height:118px;object-fit:cover;background:#02050a}.physics-guide-card div{display:grid;align-content:center;gap:4px;padding:10px}.physics-guide-card time{color:#69dcff;font-weight:900}.physics-guide-card span{font-size:10px;font-weight:900;letter-spacing:.08em;color:#9d81ff}.physics-guide-card strong{font:800 1rem/1.08 Georgia,serif}.physics-guide-card small{color:#91a4b7}@media(max-width:850px){.physics-guide-grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.physics-weekly-head{align-items:start;flex-direction:column}.physics-guide-grid{grid-template-columns:1fr}.physics-guide-card{grid-template-columns:112px 1fr}.physics-guide-card img{width:112px}}`;
  document.head.appendChild(style);
  guide.innerHTML=`<div class="physics-weekly"><div class="physics-weekly-head"><div><p>SEVEN-DAY CHANNEL SCHEDULE</p><h2>Physics TV guide</h2></div><span>New lineup at 12:00 AM local time</span></div><div class="physics-day-tabs"></div><h3 class="physics-guide-date"></h3><div class="physics-guide-grid"></div></div>`;
  const tabs=guide.querySelector(".physics-day-tabs"),date=guide.querySelector(".physics-guide-date"),grid=guide.querySelector(".physics-guide-grid");
  function render(){tabs.innerHTML=days.map((d,i)=>`<button type="button" data-day="${i}"${i===selected?' aria-current="date"':''}>${safe(fmtDay(d.startsAtMs))}</button>`).join("");date.textContent=fmtLong(days[selected].startsAtMs);const blocks=days[selected].blocks.filter(b=>selected>0||b.endsAtMs>now);grid.innerHTML=blocks.map(card).join("");}
  tabs.addEventListener("click",e=>{const b=e.target.closest("button[data-day]");if(!b)return;selected=Number(b.dataset.day)||0;render();});render();
})();
